# Generated by Django 4.1.4 on 2022-12-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_model', '0003_group_remove_person_shirt_size_alter_album_artist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonNormal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('shirt_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
            ],
        ),
    ]
