# Generated by Django 4.1.4 on 2022-12-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_model', '0004_personnormal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
