# Generated by Django 4.1.4 on 2022-12-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_model', '0007_employee_timesheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.AlterOrderWithRespectTo(
            name='timesheet',
            order_with_respect_to='employee',
        ),
    ]
