# Generated by Django 4.1.4 on 2022-12-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_model', '0008_rename_employee_id_timesheet_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'permissions': [('can_deliver_fruit', 'Can deliver fruits')],
            },
        ),
    ]
